language: php

cache:
  apt: true

php:
  - '7.0'
  - '7.1'

sudo: false

addons:
  hosts:
    - australienlive.github.io

before_install:
  - phpenv config-rm xdebug.ini

install:
  - composer install --no-interaction

before_script:
  - phantomjs --webdriver=4444 >/dev/null 2>&1 &
  - vendor/bin/sculpin generate --server --port 80 > /dev/null 2>&1 &
  - sleep 2

script:
  - vendor/bin/codecept run

cache:
  directories:
    - vendor
    - $HOME/.composer/cache
