language: php

cache:
  apt: true

php:
  - '5.6'
  - '7.0'
  - '7.1'

sudo: false

install:
  - composer install --no-interaction

before_script:
  - phantomjs --webdriver=4444 >/dev/null 2>&1 &
  - vendor/bin/sculpin generate --server --port 4000 > /dev/null 2>&1 &

script:
  - vendor/bin/codecept run
