language: php

cache:
  apt: true
  directories:
    - vendor
    - $HOME/.composer/cache

php:
  - '7.1'

matrix:
  fast_finish: true

sudo: false

before_install: phpenv config-rm xdebug.ini

install:
  - composer install --no-interaction

before_script:
  - phantomjs --webdriver=4444 >/dev/null 2>&1 &
  - vendor/bin/sculpin generate --server --port 4000 > /dev/null 2>&1 &
  - sleep 2

script:
  - vendor/bin/codecept run

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: output_dev/
  repo: AustralienLive/australienlive.github.io
  target_branch: master

